name: CI/CT/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.9' # Set this to the Julia version you want to use
    - name: Install dependencies
      run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'
    - name: Run tests
      run: julia --project=@. -e 'using Pkg; Pkg.test()'
